const motherTongue = [
    'Abkhaz',
    'Afrikaans',
    'Amharic',
    'Arabic',
    'Armenian',
    'Azerbaijani',
    'Bambara',
    'Basque',
    'Belorussian',
    'Bengali',
    'Bosnian',
    'Bulgarian',
    'Burmese',
    'Burushaski',
    'Catalan',
    'Chinese Simplified',
    'Chinese Traditional',
    'Croatian',
    'Czech',
    'Danish',
    'Dutch',
    'English',
    'Estonian',
    'Ewe',
    'Filipino',
    'Finnish',
    'French',
    'French (Can.)',
    'Fula/Fulah/Fulani',
    'Galician',
    'Georgian',
    'German',
    'Greek',
    'Hausa',
    'Hebrew',
    'Hindi',
    'Hungarian',
    'Icelandic',
    'Indonesian',
    'Irish',
    'Italian',
    'Japanese',
    'Kannada',
    'Kazakh',
    'Kinyarwanda',
    'Kirghiz',
    'Kirundi',
    'Korean',
    'Latvian',
    'Lithuanian',
    'Luo',
    'Macedonian',
    'Malaysian',
    'Maltese',
    'Nepali',
    'Norwegian',
    'Pashto',
    'Persian',
    'Polish',
    'Portuguese',
    'Portuguese (Braz.)',
    'Romanian',
    'Russian',
    'Serbian',
    'Sinhala',
    'Slovak',
    'Slovenian',
    'Somali',
    'Spanish',
    'Swahili',
    'Swedish',
    'Tamil',
    'Telugu',
    'Thai',
    'Turkish',
    'Ukrainian',
    'Urdu',
    'Uzbek',
    'Vietnamese',
    'Welsh',
    'Wolof',
    'Xhosa',
    'Yiddish',
    'Yoruba',
    'Zulu'
  ]

  accessibleAutocomplete({
    element: document.querySelector('#my-autocomplete-container'),
    id: 'my-autocomplete', // To match it to the existing <label>.
    source: motherTongue,
    'defaultValue': 'English',
    autoselect: true
  })